version: "3.7"
services:
  server:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    entrypoint: ./.docker/entrypoint.sh
    networks:
      - kafka_example_network
    ports:
      - "$PORT:3000"
    env_file:
      - ./.env
    environment:
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - "./:/var/www/app"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
networks:
  kafka_example_network:
    driver: bridge
