version: '3.7'

services:
  app:
    build: .
    container_name: app_laravel_code_education
    volumes: 
      - ./:/var/www
    networks: 
      - code_education_app_networks
  nginx:
    build: .docker/nginx
    container_name: nginx_code_education
    restart: always
    tty: true
    ports: 
      - "8000:80"
    volumes: 
      - ./:/var/www
    networks: 
      - code_education_app_networks

  redis:
    image: redis:alpine
    expose: 
      - 6379
    networks: 
      - code_education_app_networks

networks: 
  code_education_app_networks:
    driver: bridge