version: '3.7'
services: 
  productapp:
    build: .
    volumes:
      - ./:/var/www/app
      - ./node_modules:/var/www/app/node_modules
    depends_on: 
      - productapp-mysql
    #   - productapp-redis
  productapp-mysql:
    image: mysql:5.7.29
    command: --innodb-use-native-aio=0
    restart: always
    ports: 
      - "3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: productapp
      MYSQL_ROOT_PASSWORD: root
  # productapp-redis:
  #   image: redis:latest
  #   restart: always
  #   ports: 
  #     - "6379"
  productapp-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:80"
    volumes: 
      - ./:/var/www
    depends_on:
      - productapp