apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "nodeserver"
    spec:
      containers:
        - name: "nodeserver"
          image: "marcusbalbi/primeiro-exemplo-kubernetes:v6.4"
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 3
            failureThreshold: 1
            # initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 10
            successThreshold: 1
            # initialDelaySeconds: 15
          envFrom:
            - configMapRef:
                name: nodeserver-env
            - secretRef:
                name: "nodeserver-secret"
          volumeMounts:
            - mountPath: "/var/www/app/myfamily"
              name: config
      volumes:
        - name: config
          configMap:
            name: "configmap-family"
            items:
              - key: members
                path: myfamily.txt
