apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "nodeserver"
    spec:
      containers:
        - name: "nodeserver"
          image: "marcusbalbi/primeiro-exemplo-kubernetes:v6.5"
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 25Mi
              

          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 3
            failureThreshold: 1
            # initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 10
            successThreshold: 1
            # initialDelaySeconds: 15
          envFrom:
            - configMapRef:
                name: nodeserver-env
            - secretRef:
                name: "nodeserver-secret"
          volumeMounts:
            - mountPath: "/var/www/app/myfamily"
              name: config
            - mountPath: "/var/www/app/pvc"
              name: nodeserver-volume
      volumes:
        - name: nodeserver-volume
          persistentVolumeClaim:
            claimName: nodeserver-pvc
        - name: config
          configMap:
            name: "configmap-family"
            items:
              - key: members
                path: myfamily.txt
